# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags/index.html
  Categories: /categories
  Github:
    url: https://github.com/Poikilo
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Poikilo's Blog

# URL of the Home page image
index_cover: https://i.ibb.co/m6yPRjD/image.png

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: poikilo-github-io
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-159158738-1

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/Poikilo
gitlab_url:
linkedin_url:
mailto: aksjm2@gmail.com